name: todo_with_firebase_08oct
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  dropdown_button2: ^2.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Onesans     
      fonts:
        - asset: assets/fonts/AROneSans-Bold.ttf
        - asset: assets/fonts/AROneSans-Medium.ttf
        - asset: assets/fonts/AROneSans-Regular.ttf
        - asset: assets/fonts/AROneSans-SemiBold.ttf
