// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuvUfTj5TVM51wm3N35e7T8xVPHfFsgUU',
    appId: '1:468064622133:web:6a1515e5d17d74c8b6037c',
    messagingSenderId: '468064622133',
    projectId: 'todoy-41366',
    authDomain: 'todoy-41366.firebaseapp.com',
    storageBucket: 'todoy-41366.appspot.com',
    measurementId: 'G-NVZ0HJ4F0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbMnh10QN0akoL2avZtymIP-Sa0uz8v9Y',
    appId: '1:468064622133:android:3ff9163b25863bf3b6037c',
    messagingSenderId: '468064622133',
    projectId: 'todoy-41366',
    storageBucket: 'todoy-41366.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBJ4AkD6uqJto2VYCTLvLGdrDJBJG8zY0',
    appId: '1:468064622133:ios:2c4b498da678ddebb6037c',
    messagingSenderId: '468064622133',
    projectId: 'todoy-41366',
    storageBucket: 'todoy-41366.appspot.com',
    iosBundleId: 'com.example.todoWithFirebase08oct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBJ4AkD6uqJto2VYCTLvLGdrDJBJG8zY0',
    appId: '1:468064622133:ios:2c4b498da678ddebb6037c',
    messagingSenderId: '468064622133',
    projectId: 'todoy-41366',
    storageBucket: 'todoy-41366.appspot.com',
    iosBundleId: 'com.example.todoWithFirebase08oct',
  );
}
